package Project;


import java.io.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class AddNewContatct extends javax.swing.JFrame {

    /**
     * Creates new form AddNewContatct
     */
    public AddNewContatct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        addNewContactPanel = new javax.swing.JPanel();
        addNewContactLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        streetLabel = new javax.swing.JLabel();
        phoneLabel1 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        emailtf = new javax.swing.JTextField();
        nametf1 = new javax.swing.JTextField();
        phonetf1 = new javax.swing.JTextField();
        addresstf = new javax.swing.JTextField();
        newAdressPrevious = new javax.swing.JButton();
        newAdressPrevious1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Address Book Application");

        addNewContactPanel.setBackground(new java.awt.Color(0, 51, 51));

        addNewContactLabel.setFont(new java.awt.Font("Broadway", 0, 48)); // NOI18N
        addNewContactLabel.setForeground(new java.awt.Color(102, 102, 102));
        addNewContactLabel.setText("Add New Contact ");

        nameLabel.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(240, 240, 240));
        nameLabel.setText("Name");

        streetLabel.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        streetLabel.setForeground(new java.awt.Color(240, 240, 240));
        streetLabel.setText("Street Address");

        phoneLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        phoneLabel1.setForeground(new java.awt.Color(240, 240, 240));
        phoneLabel1.setText("Phone No");

        emailLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        emailLabel1.setForeground(new java.awt.Color(240, 240, 240));
        emailLabel1.setText("Email");

        emailtf.setBackground(new java.awt.Color(0, 0, 0));
        emailtf.setForeground(new java.awt.Color(240, 240, 240));

        nametf1.setBackground(new java.awt.Color(0, 0, 0));
        nametf1.setForeground(new java.awt.Color(240, 240, 240));

        phonetf1.setBackground(new java.awt.Color(0, 0, 0));
        phonetf1.setForeground(new java.awt.Color(240, 240, 240));

        addresstf.setBackground(new java.awt.Color(0, 0, 0));
        addresstf.setForeground(new java.awt.Color(240, 240, 240));

        newAdressPrevious.setBackground(new java.awt.Color(51, 51, 51));
        newAdressPrevious.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        newAdressPrevious.setForeground(new java.awt.Color(240, 240, 240));
        newAdressPrevious.setText("Previous");
        newAdressPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAdressPreviousActionPerformed(evt);
            }
        });

        newAdressPrevious1.setBackground(new java.awt.Color(51, 51, 51));
        newAdressPrevious1.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        newAdressPrevious1.setForeground(new java.awt.Color(240, 240, 240));
        newAdressPrevious1.setText("Save");
        newAdressPrevious1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAdressPrevious1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addNewContactPanelLayout = new javax.swing.GroupLayout(addNewContactPanel);
        addNewContactPanel.setLayout(addNewContactPanelLayout);
        addNewContactPanelLayout.setHorizontalGroup(
                addNewContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addNewContactPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(addNewContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(newAdressPrevious)
                                        .addGroup(addNewContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewContactPanelLayout.createSequentialGroup()
                                                        .addComponent(emailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(emailtf, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewContactPanelLayout.createSequentialGroup()
                                                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(nametf1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(addNewContactPanelLayout.createSequentialGroup()
                                                        .addComponent(phoneLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(phonetf1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(addNewContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewContactPanelLayout.createSequentialGroup()
                                                        .addComponent(streetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(addresstf, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(newAdressPrevious1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(35, Short.MAX_VALUE))
        );
        addNewContactPanelLayout.setVerticalGroup(
                addNewContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addNewContactPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(addNewContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(addNewContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(addNewContactPanelLayout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(48, 48, 48))
                                        .addGroup(addNewContactPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(nametf1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36)))
                                .addGroup(addNewContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(addNewContactPanelLayout.createSequentialGroup()
                                                .addComponent(phoneLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(53, 53, 53))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewContactPanelLayout.createSequentialGroup()
                                                .addComponent(phonetf1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)))
                                .addGroup(addNewContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(emailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailtf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(addNewContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(streetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addresstf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(107, 107, 107)
                                .addGroup(addNewContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newAdressPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(newAdressPrevious1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addNewContactPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addNewContactPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void newAdressPreviousActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();
        new OptionPage().setVisible(true); }

    private void newAdressPrevious1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if( ( nametf1.getText().equals("") ) ||
                (phonetf1.getText().equals("") )
                || (emailtf.getText().equals("") ) ||
                (addresstf.getText().equals("") ) ) {}
        else{
            try {
                FileWriter file;
                file = new FileWriter("File/A.txt",true);
                PrintWriter write = new PrintWriter(file);
                write.println(nametf1.getText()+"-"+phonetf1.getText()+"-"
                        +emailtf.getText()+"-"+addresstf.getText());
                write.close();
                this.dispose();
                new OptionPage().setVisible(true);
            }
            catch (IOException s ){
                s.printStackTrace();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewContatct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewContatct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewContatct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewContatct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewContatct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel addNewContactLabel;
    private javax.swing.JPanel addNewContactPanel;
    private javax.swing.JTextField addresstf;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JTextField emailtf;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nametf1;
    private javax.swing.JButton newAdressPrevious;
    private javax.swing.JButton newAdressPrevious1;
    private javax.swing.JLabel phoneLabel1;
    private javax.swing.JTextField phonetf1;
    private javax.swing.JLabel streetLabel;
    // End of variables declaration
}
