package Project;


import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class SearchContact extends javax.swing.JFrame {

    /**
     * Creates new form SearchContact
     */
    public SearchContact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        serachContactPanel = new javax.swing.JPanel();
        searchContactLabel1 = new javax.swing.JLabel();
        searchphone = new javax.swing.JLabel();
        searchName1 = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        numbertf = new javax.swing.JTextField();
        searchContactPrevious = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchContactArea = new javax.swing.JTextArea();
        searchContactPrevious1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        serachContactPanel.setBackground(new java.awt.Color(0, 51, 51));

        searchContactLabel1.setFont(new java.awt.Font("Broadway", 0, 48)); // NOI18N
        searchContactLabel1.setForeground(new java.awt.Color(102, 102, 102));
        searchContactLabel1.setText("Search Contact");

        searchphone.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        searchphone.setForeground(new java.awt.Color(240, 240, 240));
        searchphone.setText("Search Number ");

        searchName1.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        searchName1.setForeground(new java.awt.Color(240, 240, 240));
        searchName1.setText("Search Name");

        nametf.setBackground(new java.awt.Color(0, 0, 0));
        nametf.setForeground(new java.awt.Color(240, 240, 240));

        numbertf.setBackground(new java.awt.Color(0, 0, 0));
        numbertf.setForeground(new java.awt.Color(240, 240, 240));

        searchContactPrevious.setBackground(new java.awt.Color(51, 51, 51));
        searchContactPrevious.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        searchContactPrevious.setForeground(new java.awt.Color(240, 240, 240));
        searchContactPrevious.setText("Previous");
        searchContactPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchContactPreviousActionPerformed(evt);
            }
        });

        searchContactArea.setBackground(new java.awt.Color(0, 0, 0));
        searchContactArea.setColumns(20);
        searchContactArea.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        searchContactArea.setForeground(new java.awt.Color(240, 240, 240));
        searchContactArea.setRows(5);
        jScrollPane1.setViewportView(searchContactArea);

        searchContactPrevious1.setBackground(new java.awt.Color(51, 51, 51));
        searchContactPrevious1.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        searchContactPrevious1.setForeground(new java.awt.Color(240, 240, 240));
        searchContactPrevious1.setText("Search");
        searchContactPrevious1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchContactPrevious1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout serachContactPanelLayout = new javax.swing.GroupLayout(serachContactPanel);
        serachContactPanel.setLayout(serachContactPanelLayout);
        serachContactPanelLayout.setHorizontalGroup(
                serachContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, serachContactPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(serachContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, serachContactPanelLayout.createSequentialGroup()
                                                .addComponent(searchContactLabel1)
                                                .addGap(68, 68, 68))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, serachContactPanelLayout.createSequentialGroup()
                                                .addGroup(serachContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(numbertf, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(48, 48, 48))))
                        .addGroup(serachContactPanelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(serachContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(serachContactPanelLayout.createSequentialGroup()
                                                .addComponent(searchContactPrevious)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(searchContactPrevious1))
                                        .addGroup(serachContactPanelLayout.createSequentialGroup()
                                                .addComponent(searchphone)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
                                .addGap(48, 48, 48))
                        .addGroup(serachContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(serachContactPanelLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(searchName1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(370, Short.MAX_VALUE)))
        );
        serachContactPanelLayout.setVerticalGroup(
                serachContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(serachContactPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(searchContactLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(serachContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(searchphone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numbertf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(serachContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(searchContactPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchContactPrevious1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58))
                        .addGroup(serachContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(serachContactPanelLayout.createSequentialGroup()
                                        .addGap(178, 178, 178)
                                        .addComponent(searchName1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(435, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(serachContactPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(serachContactPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void searchContactPreviousActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();
        new OptionPage().setVisible(true);
    }
    private void searchContactPrevious1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String name = nametf.getText();
        String number = numbertf.getText();
        int i , j = 0   ;
        try{
            ArrayList<People> array = new ArrayList<>();
            FileReader file = new FileReader("File/A.txt");
            BufferedReader r = new BufferedReader(file);
            String line ;
            searchContactArea.setText("");
            while ( (line = r.readLine() ) != null  ){
                String[] part = line.split("-");
                People people = new People(part[0],part[1],part[2],part[3]) ;
                array.add(people);
            }
            for (  i = 0 ; i < array.size() ; i++ ){
                if(  name.equals(array.get(i).name) && number.equals(array.get(i).phone_Number)  ){
                    searchContactArea.append("Name                : " +array.get(i).name + "\n"
                            +"Phone Number : " +array.get(i).phone_Number + "\n"
                            +"Email                : "+ array.get(i).email + "\n"
                            +"Address            : "+ array.get(i).address + "\n\n");}

                else{j++  ;} }

            if ( j == array.size() ){
                searchContactArea.setText("Sorry ! Contact Not Found !");
            }  r.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Contacts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (java.io.IOException ex) {
            Logger.getLogger(Contacts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchContact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nametf;
    private javax.swing.JTextField numbertf;
    private javax.swing.JTextArea searchContactArea;
    private javax.swing.JLabel searchContactLabel1;
    private javax.swing.JButton searchContactPrevious;
    private javax.swing.JButton searchContactPrevious1;
    private javax.swing.JLabel searchName1;
    private javax.swing.JLabel searchphone;
    private javax.swing.JPanel serachContactPanel;
    // End of variables declaration
}
